# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: novitas@2018
  host: localhost

development:
  <<: *default
  database: novitas
  password: rootpath

test:
  <<: *default
  database: novitas
  password: rootpath

production:
  <<: *default
  database: novitas
